create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) >= 2),
  usn text not null unique,
  email text not null unique,
  phone text not null unique,
  registration_code text not null unique check (registration_code ~ '^[A-Z0-9]{6}$'),
  qr_data jsonb not null,
  registered_at timestamptz not null default now(),
  attendance_status boolean not null default false,
  checked_in_at timestamptz,
  checked_in_by text,
  scan_device text
);

create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  registration_code text,
  participant_name text,
  scan_result text not null check (scan_result in ('Success', 'Duplicate Scan', 'Invalid QR')),
  scanner_device text
);

alter table public.participants enable row level security;
alter table public.attendance_logs enable row level security;

drop policy if exists "Participants can register" on public.participants;

drop policy if exists "Read participants for event operations" on public.participants;
create policy "Read participants for event operations"
on public.participants for select
using (auth.role() = 'authenticated');

drop policy if exists "Read attendance logs" on public.attendance_logs;
create policy "Read attendance logs"
on public.attendance_logs for select
using (auth.role() = 'authenticated');

create or replace function public.register_event_participant(
  participant_name text,
  participant_usn text,
  participant_email text,
  participant_phone text,
  generated_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created_participant participants%rowtype;
  final_participant participants%rowtype;
begin
  insert into participants(name, usn, email, phone, registration_code, qr_data)
  values (
    trim(participant_name),
    upper(trim(participant_usn)),
    lower(trim(participant_email)),
    trim(participant_phone),
    upper(generated_code),
    jsonb_build_object('eventId', 'coffee-alumni-2026', 'participantId', 0, 'code', upper(generated_code))
  )
  returning * into created_participant;

  update participants
  set qr_data = jsonb_build_object(
    'eventId', 'coffee-alumni-2026',
    'participantId', created_participant.id,
    'code', created_participant.registration_code
  )
  where id = created_participant.id
  returning * into final_participant;

  return to_jsonb(final_participant);
end;
$$;

grant execute on function public.register_event_participant(text, text, text, text, text) to anon, authenticated;

create or replace function public.retrieve_participant_by_usn(participant_usn text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  found_participant participants%rowtype;
begin
  select * into found_participant
  from participants
  where usn = upper(trim(participant_usn))
  limit 1;

  if not found then
    return null;
  end if;

  return to_jsonb(found_participant);
end;
$$;

create or replace function public.retrieve_participant_by_id(participant_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  found_participant participants%rowtype;
begin
  select * into found_participant
  from participants
  where id = participant_id
  limit 1;

  if not found then
    return null;
  end if;

  return to_jsonb(found_participant);
end;
$$;

grant execute on function public.retrieve_participant_by_usn(text) to anon, authenticated;
grant execute on function public.retrieve_participant_by_id(bigint) to anon, authenticated;

create or replace function public.mark_event_attendance(
  qr_payload_text text,
  volunteer_name text,
  scanner_device_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  payload jsonb;
  target_event_id text;
  target_participant_id bigint;
  target_code text;
  found_participant participants%rowtype;
  updated_participant participants%rowtype;
begin
  begin
    payload := qr_payload_text::jsonb;
  exception when others then
    insert into attendance_logs(registration_code, participant_name, scan_result, scanner_device)
    values (null, null, 'Invalid QR', scanner_device_name);
    return jsonb_build_object('status', 'invalid', 'message', 'Invalid or Unregistered QR Code');
  end;

  target_event_id := payload->>'eventId';
  target_code := upper(payload->>'code');

  if (payload->>'participantId') !~ '^[0-9]+$' then
    target_participant_id := null;
  else
    target_participant_id := (payload->>'participantId')::bigint;
  end if;

  if target_event_id is distinct from 'coffee-alumni-2026' or target_participant_id is null or target_code is null then
    insert into attendance_logs(registration_code, participant_name, scan_result, scanner_device)
    values (target_code, null, 'Invalid QR', scanner_device_name);
    return jsonb_build_object('status', 'invalid', 'message', 'QR does not belong to this event.');
  end if;

  select * into found_participant
  from participants
  where id = target_participant_id
    and registration_code = target_code
    and qr_data->>'eventId' = 'coffee-alumni-2026'
  limit 1;

  if not found then
    insert into attendance_logs(registration_code, participant_name, scan_result, scanner_device)
    values (target_code, null, 'Invalid QR', scanner_device_name);
    return jsonb_build_object('status', 'invalid', 'message', 'Invalid or Unregistered QR Code');
  end if;

  if found_participant.attendance_status then
    insert into attendance_logs(registration_code, participant_name, scan_result, scanner_device)
    values (found_participant.registration_code, found_participant.name, 'Duplicate Scan', scanner_device_name);
    return jsonb_build_object(
      'status', 'duplicate',
      'message', 'Previous Check-In Time: ' || found_participant.checked_in_at,
      'checked_in_at', found_participant.checked_in_at,
      'participant', to_jsonb(found_participant)
    );
  end if;

  update participants
  set attendance_status = true,
      checked_in_at = now(),
      checked_in_by = volunteer_name,
      scan_device = scanner_device_name
  where id = found_participant.id
    and attendance_status = false
  returning * into updated_participant;

  insert into attendance_logs(registration_code, participant_name, scan_result, scanner_device)
  values (updated_participant.registration_code, updated_participant.name, 'Success', scanner_device_name);

  return jsonb_build_object(
    'status', 'success',
    'message', 'Checked In Successfully',
    'checked_in_at', updated_participant.checked_in_at,
    'participant', to_jsonb(updated_participant)
  );
end;
$$;

grant execute on function public.mark_event_attendance(text, text, text) to authenticated;

alter publication supabase_realtime add table public.participants;
alter publication supabase_realtime add table public.attendance_logs;
